workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    instance_type: mac_mini
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: master
          include: true
          source: true
    scripts:

      # This is where the script to run mobsfscan is placed
      - name: Mobsfscan static analysis
        script: |
          pip3 install --upgrade mobsfscan
          mobsfscan .

      - name: Set up debug key.properties
        script: |
          keytool -genkeypair \
          -alias androiddebugkey_ \
          -keypass android \
          -keystore ~/.android/debug.keystore \
          -storepass android \
          -dname 'CN=Android Debug,O=Android,C=US' \
          -keyalg 'RSA' \
          -keysize 2048 \
          -validity 10000
    artifacts:
      - app/build/outputs/**/**/*.apk